include:
  - project: 'famedly/company/frontend/ci-templates'
    ref: main
    file: '/all.yml'

unit_tests:
  image: archlinux:latest # google/dart doesn't have openssl
  stage: test
  needs: []
  coverage: '/^\s+lines.+: (\d+.\d*%)/'
  script:
    - pacman --noconfirm -Syu
    - pacman --noconfirm -S dart
    - useradd -m test
    - chown -R 'test:' '.'
    - su -c 'dart pub get' test
    - su -c 'dart test' test
  artifacts:
    paths:
      - coverage/
