# This file configures the analyzer to use the lint rule set from `package:lint`

include: package:lint/package.yaml

analyzer:
  exclude:
    - 'lib/src/generated/ffi.dart'

linter:
  rules:
    prefer_double_quotes: true
    unawaited_futures: true
    discarded_futures: true
