name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # TODO: Remove once https://github.com/dart-lang/sdk/issues/55745
        #       has been resolved
        sdk: [stable, 3.3.0]
        exclude:
          - os: macos-latest
            sdk: 3.3.0
          - os: ubuntu-latest
            sdk: 3.3.0
          - os: windows-latest
            sdk: stable
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Install OpenSSL (Windows)
        run: choco install openssl
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Run tests with coverage
        run: dart run coverage:test_with_coverage

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
          name: Upload to codecov.io
          verbose: true
