name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Install OpenSSL (Windows)
        run: |
          choco install openssl
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Run tests with coverage
        run: dart test --coverage="coverage"

      - name: Convert coverage to ICOV
        run: dart run coverage:format_coverage --lcov --in=coverage --out=coverage.lcov --report-on=lib

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.lcov
          name: Upload to codecov.io
          verbose: true
